spring:
  application:
    name: OAuth2-Application
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lipcr6ck1EKthJMN
            clientSecret: 165e088741445030fe708732f6890f520e716dc3
            scope: user:email
          google:
            clientId: 812042630226-9ogj4pkcmh7l7lsjbmvu7cp9b583ki7t.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE


