CREATE TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title VARCHAR,
   author VARCHAR,
   publication_year SMALLINT,
   CONSTRAINT pk_books PRIMARY KEY (id)
);

INSERT INTO books (title, author, publication_year) VALUES ('Java', 'Anyone', 2012);
INSERT INTO books (title, author, publication_year) VALUES ('Kotlin', 'Anyone 2', 2011);
INSERT INTO books (title, author, publication_year) VALUES ('Scala', 'Anyone 3', 2015);